### ISSUE TITLE
Custom_deps - why remove existing dependencies?

### ISSUE THREAD

**Issue by bouwew** [home-assistant/hassio-addons-development#5]
I needed to install a module from Pypi on Hassio. After some searching I found the custom_deps addon.
I did what was needed, but it also deleted all my existing deps that were installed when I had added several Custom_Components. I think this is unwanted behavior as it breaks these installed components, so, a bug?

**Comment by frenck** [comment]
A custom component should specify its deps. If it does that correctly, Home Assistant will install those deps automatically.

If you need to manually install deps for a custom component, the custom component is not correctly written.

That being said, the add-on has been moved to the developer-hassio-addons repository, so it is still available, but moved.
