### ISSUE TITLE
custom_deps add-on's pypi option naming confusing

### ISSUE THREAD

**Issue by pdecat** [home-assistant/hassio-addons-development#6]
Hi, I've just come across this awesome and helpful add-on via https://github.com/zigpy/zigpy-zigate/pull/29.

The custom_deps' [pypi option](https://github.com/home-assistant/hassio-addons-development/blob/f5824f0538c9224dec69400f2d2904e6c2270ab1/custom_deps/config.json#L12) is really a list of pip packages which is simply passed to `pip install`: https://github.com/home-assistant/hassio-addons-development/blob/aa8c7a416c73aec5b4e41aac31880770b6f1c586/custom_deps/run.sh#L28

So packages can not only come from pypi but also from other sources such as git repositories which is helpful to testing branches before merging PRs and releasing new versions of packages.

For example, the following config works great:

```
pypi:
  - 'git+https://github.com/pdecat/zha-device-handlers@dm/legrand-devices'
apk: []
```

Maybe it should be renamed from `pypi` to `pip` to avoid confusion or, to avoid breaking changes, be documented to make this more obvious.

I'd be happy to submit a PR if this makes sense to you. Thanks!

**Comment by pdecat** [comment]
Hi @pvizeli @frenck, looks like this went under your radar which I would totally understand.

Happy to close if you feel it's a non issue.

Best regards!

**Comment by frenck** [comment]
I don't think for an add-on which has a very specific use-case, this needs to be fixed or adjusted.
Changing the config is also a breaking change.

**Comment by pdecat** [comment]
Ok then :)
