### ISSUE TITLE
custom_deps stops working

### ISSUE THREAD

**Issue by sanyatuning** [home-assistant/hassio-addons-development#7]
Hi!

The custom_deps addon stopped working for me.
I assume the problem is that the addon uses folder "/config/deps/lib/python3.7/" to install packages, but my Supervised Core is running python 3.8.

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.3
supervisor | 229
timezone | Europe/Budapest
version | 0.113.2
virtualenv | false

**Comment by brefra** [comment]
I do experience the same issue. As a workaround I renamed the “python3.7” folder into “python3.8” after running deps. But it’s better to get this fixed properly though.

**Comment by frenck** [comment]
In theory, this add-on should not be used. Dependencies are loaded as part of the integration manifests. Any specific use case for you guys?

**Comment by brefra** [comment]
I do understand it not for a regular user. I’m using this add-on to “move” a specific 3rd party lib to a folder underneath `config` at my hassio based production system (rpi 4). This allows me to remotely make some changes to the “moved” lib for debug/testing purposes. Mainly for the ones I do some contributions to.
I don’t have duplicate hardware to setup a separate representative development environment. If there’s a better/easier way I’m happy to know.

**Comment by frenck** [comment]
@brefra There is, copy the integration to the `custom_components` folder, that would give a more accurate representation of what you are doing.

**Comment by sanyatuning** [comment]
I used this addon to test beta versions of zigpy-cc lib, which is used by ZHA integration.

**Comment by sanyatuning** [comment]
@frenck you mean I need to copy the whole ZHA integration to cusom_components?
Will this override the original integration or I need to rename it?
What is the real purpose of this addon?

**Comment by brefra** [comment]
Yes a copied integration will kind of "overwrite" the original one.

When you've copied the integration files over to the `custom_components` folder you can alter the vale of the `requirements` property listed at the `manifest.json` file, to use for example (your forked) github hosted version of the lib. Like described [here](https://developers.home-assistant.io/docs/creating_integration_manifest#requirements)
